package com.example.hospital.managment.service;

import com.example.hospital.managment.entity.MedicalRecord;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

import java.io.ByteArrayOutputStream;

@Service
public class PrescriptionPdfService {

    public byte[] generatePrescriptionPDF(MedicalRecord record) {

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4);

        try {
            PdfWriter.getInstance(document, baos);
            document.open();

            // Title
            Font titleFont = new Font(Font.HELVETICA, 20, Font.BOLD);
            Paragraph title = new Paragraph("Prescription Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            document.add(new Paragraph("\n-------------------------------------------\n"));

            // Patient Info
            document.add(new Paragraph("Patient Name: " + record.getPatient().getFirstName()+" " + record.getPatient().getLastName()));
            document.add(new Paragraph("Doctor Name: " + record.getDoctor().getFullName()));
            document.add(new Paragraph("Date: " + record.getDate().toString()));

            document.add(new Paragraph("\nDiagnosis:"));
            document.add(new Paragraph(record.getDiagnosis()));

            document.add(new Paragraph("\nPrescription:"));
            document.add(new Paragraph(record.getPrescription()));

            document.add(new Paragraph("\n-------------------------------------------"));
            document.add(new Paragraph("Generated by Hospital Management System"));

            document.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        return baos.toByteArray();
    }
}
